name: fhir-to-markdown-converter
services:
- name: web
  source_dir: /
  github:
    repo: your-username/fhir-converter
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080" 